# Generated by Django 4.1 on 2024-05-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrichiact",
            name="nom_fichier",
            field=models.CharField(max_length=64, verbose_name="nom du fichier"),
        ),
        migrations.AlterField(
            model_name="enrichidoc",
            name="nom_fichier",
            field=models.CharField(max_length=64, verbose_name="nom du fichier"),
        ),
        migrations.AlterField(
            model_name="enrichidynamique",
            name="nom_fichier",
            field=models.CharField(max_length=64, verbose_name="nom du fichier"),
        ),
        migrations.AlterField(
            model_name="enrichilieu",
            name="nom_fichier",
            field=models.CharField(max_length=64, verbose_name="nom du fichier"),
        ),
        migrations.AlterField(
            model_name="enrichinouvelle",
            name="nom_fichier",
            field=models.CharField(max_length=64, verbose_name="nom du fichier"),
        ),
        migrations.AlterField(
            model_name="enrichiperception",
            name="nom_fichier",
            field=models.CharField(max_length=64, verbose_name="nom du fichier"),
        ),
        migrations.AlterField(
            model_name="enrichitemps",
            name="nom_fichier",
            field=models.CharField(max_length=64, verbose_name="nom du fichier"),
        ),
        migrations.AlterField(
            model_name="simple",
            name="nom_fichier",
            field=models.CharField(max_length=64, verbose_name="nom_fichier"),
        ),
    ]
