# Generated by Django 4.1 on 2024-04-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnrichiAct",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nom_fichier",
                    models.CharField(max_length=32, verbose_name="nom du fichier"),
                ),
                (
                    "num_phrase",
                    models.BigIntegerField(verbose_name="numéro de la phrase"),
                ),
                ("dynamique", models.TextField(verbose_name="dynamique")),
                ("segment_annote", models.TextField(verbose_name="segment annoté act")),
                (
                    "act_type",
                    models.CharField(
                        max_length=16, verbose_name="attribut du type des acts"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnrichiDoc",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nom_fichier",
                    models.CharField(max_length=32, verbose_name="nom du fichier"),
                ),
                (
                    "num_phrase",
                    models.BigIntegerField(verbose_name="numéro de la phrase"),
                ),
                ("dynamique", models.TextField(verbose_name="dynamique")),
                (
                    "segment_annote",
                    models.TextField(verbose_name="segment annoté de la doc"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnrichiDynamique",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nom_fichier",
                    models.CharField(max_length=32, verbose_name="nom du fichier"),
                ),
                (
                    "num_phrase",
                    models.BigIntegerField(verbose_name="numéro de la phrase"),
                ),
                ("segment_annote", models.TextField(verbose_name="segment annoté")),
                ("accompli", models.CharField(max_length=32, verbose_name="accompli")),
                ("nature", models.CharField(max_length=32, verbose_name="nature")),
                ("proces", models.CharField(max_length=32, verbose_name="proces")),
                ("temps", models.CharField(max_length=32, verbose_name="temps")),
            ],
        ),
        migrations.CreateModel(
            name="EnrichiLieu",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nom_fichier",
                    models.CharField(max_length=32, verbose_name="nom du fichier"),
                ),
                (
                    "num_phrase",
                    models.BigIntegerField(verbose_name="numéro de la phrase"),
                ),
                ("dynamique", models.TextField(verbose_name="dynamique")),
                (
                    "segment_annote",
                    models.TextField(verbose_name="segment annoté du lieu"),
                ),
                (
                    "type",
                    models.CharField(
                        max_length=16, verbose_name="attribut type de lieu"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnrichiNouvelle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nom_fichier",
                    models.CharField(max_length=32, verbose_name="nom du fichier"),
                ),
                (
                    "num_phrase",
                    models.BigIntegerField(verbose_name="numéro de la phrase"),
                ),
                ("dynamique", models.TextField(verbose_name="dynamique")),
                (
                    "segment_annote",
                    models.TextField(verbose_name="segment annoté de la nouvelle"),
                ),
                (
                    "type_nouvelle",
                    models.CharField(
                        choices=[(1, "cause"), (2, "res"), (3, "obj")],
                        max_length=16,
                        verbose_name="attribut",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnrichiPerception",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nom_fichier",
                    models.CharField(max_length=32, verbose_name="nom du fichier"),
                ),
                (
                    "num_phrase",
                    models.BigIntegerField(verbose_name="numéro de la phrase"),
                ),
                ("dynamique", models.TextField(verbose_name="dynamique")),
                (
                    "segment_annote",
                    models.TextField(verbose_name="segment annoté de la perception"),
                ),
                (
                    "perc_type",
                    models.CharField(
                        max_length=16, verbose_name="attribut du type de la perception"
                    ),
                ),
                ("pol", models.CharField(max_length=16, verbose_name="attribut pol")),
            ],
        ),
        migrations.CreateModel(
            name="EnrichiTemps",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nom_fichier",
                    models.CharField(max_length=32, verbose_name="nom du fichier"),
                ),
                (
                    "num_phrase",
                    models.BigIntegerField(verbose_name="numéro de la phrase"),
                ),
                ("dynamique", models.TextField(verbose_name="dynamique")),
                (
                    "segment_annote",
                    models.TextField(verbose_name="segment annoté du temps"),
                ),
                (
                    "axe_temps",
                    models.CharField(max_length=16, verbose_name="attribut temps"),
                ),
                (
                    "absolu",
                    models.CharField(max_length=16, verbose_name="attribut absolu"),
                ),
                ("type", models.CharField(max_length=16, verbose_name="attribut type")),
            ],
        ),
        migrations.CreateModel(
            name="Simple",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nom_fichier",
                    models.CharField(max_length=32, verbose_name="nom_fichier"),
                ),
                ("num_phrase", models.BigIntegerField(verbose_name="num_phrase")),
                ("dynamique", models.TextField(verbose_name="dynamique")),
                ("lieu_objet", models.TextField(verbose_name="lieu_objet")),
                ("lieu_loc", models.TextField(verbose_name="lieu_loc")),
                ("temps", models.TextField(verbose_name="temps")),
                ("acteurs", models.TextField(verbose_name="acteurs")),
                ("perc", models.TextField(verbose_name="perc")),
                ("doc", models.TextField(verbose_name="doc")),
            ],
        ),
    ]
