# Generated by Django 4.1 on 2024-05-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_alter_enrichiact_nom_fichier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrichinouvelle",
            name="segment_annote",
        ),
        migrations.RemoveField(
            model_name="enrichinouvelle",
            name="type_nouvelle",
        ),
        migrations.AddField(
            model_name="enrichinouvelle",
            name="cause",
            field=models.TextField(
                default=0, verbose_name="segment annoté cause de la nouvelle"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrichinouvelle",
            name="obj",
            field=models.TextField(
                default=0, verbose_name="segment annoté obj de la nouvelle"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enrichinouvelle",
            name="res",
            field=models.TextField(
                default=0, verbose_name="segment annoté res de la nouvelle"
            ),
            preserve_default=False,
        ),
    ]
